#!/bin/bash
# CURRENTLY OSX / BREW ONLY
# Sorry it's what I test on. It'll get there

echo "Checking for brew installation..."
if ! [ -x "$(command -v brew)" ]; then
  echo 'Installing brew...'
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
  echo "OK"
fi

echo "Checking for python..."
if ! [ -x "$(command -v python3)" ]; then
  echo "Installing Python..."
  brew install python3
else
  echo "OK"	
fi

echo "Checking for PIP3"
if ! [ -x "$(command -v pip3)" ]; then
  echo "Installing pip3..."
  brew install pip3
else
  echo "OK"
fi

echo "Installing required libraries..."
pip3 install PIL
pip3 install tkinter

echo "DONE"
exit 0